spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/jamu
    password: Asdfg123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        type: TRACE
        SQL: DEBUG
